name: sikora00/rxjs-overlay PR workflow

on:
  pull_request:
    paths:
      - 'packages/rxjs-overlay/*'

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}${{ hashFiles('packages/rxjs-overlay/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: prettier check
        run: npm run format:check
      - name: bootstrap
        run: npm run lerna -- bootstrap --scope=@sikora00/nestjs-slack-bot
      - name: build
        run: npm run lerna -- run build --scope=@sikora00/nestjs-slack-bot
      - name: test
        run: npm run lerna -- run test --scope=@sikora00/nestjs-slack-bot
